export const routes = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    otp: "/auth/otp-verification",
    verifyLoginOtp: "/auth/verify-login-otp",
  },
  dashboard: {
    dashboard: "/dashboard",
    profile: "/dashboard/profile",
    support: "/dashboard/support",
  },
  vendorDashboard: {
    root: "/vendor-dashboard",
    paymentVoucher: "/vendor-dashboard/payment-voucher",
    transactionHistory: "/vendor-dashboard/transaction-history",
    reports: "/vendor-dashboard/reports",
    profile: "/vendor-dashboard/profile",
    support: "/vendor-dashboard/support",
  },
  parishDashboard: {
    root: "/parish-dashboard",
    importContributors: "/parish-dashboard/import-contributors",
    searchUser: "/parish-dashboard/monthly-contribution/search-user",
    monthlyContribution: "/parish-dashboard/monthly-contribution",
    monthlyRemittance: "/parish-dashboard/monthly-remittance",
    pensioners: "/parish-dashboard/pensioners",
    settings: "/parish-dashboard/settings",
    support: "/parish-dashboard/support",
  },
  dioceseDashboard: {
    root: "/diocese-dashboard",
    importContributors: "/diocese-dashboard/import-contributors",
    dioceseManagement: "/diocese-dashboard/diocese-management",
    ParishManagement: "/diocese-dashboard/parish-management",
    monthlyRemittance: "/diocese-dashboard/monthly-remittance",
    pensioners: "/diocese-dashboard/pensioners",
    settings: "/diocese-dashboard/settings",
    support: "/diocese-dashboard/support",
    approveKyc: "diocese-dashboard/approve-kyc",
    viewDetails: "/diocese-dashboard/parish-management/view-details",
    enterContributor: "/diocese-dashboard/parish-management/enter-contributors",
    profileSettings: "/diocese-dashboard/settings/profile-settings",
  },
  venerableDashboard: {
    root: "/venerable-dashboard",
    dioceseDirectory: "/venerable-dashboard/diocese-directory",
    userManagement: "/venerable-dashboard/user-management",
    systemUsers: "/venerable-dashboard/system-users",
    settings: "/venerable-dashboard/settings",
    support: "/venerable-dashboard/support",
  },
  financeDashboard: {
    root: "/finance-dashboard",
    pensionManagement: "/finance-dashboard/pension-management",
    vendorManagement: "/finance-dashboard/vendor-management",
    monthlyContributions: "/finance-dashboard/monthly-contributions",
    settings: "/finance-dashboard/settings",
    support: "/finance-dashboard/support",
  },
};
