export const dioceses = [
  "On the Niger",
  "Awka",
  "Nnewi",
  "Aguata",
  "Ogbaru",
  "Ihiala",
  "Niger West",
  "Niger East",
  "Amichi",
  "Niger Delta",
  "Calabar",
  "Uyo",
  "Niger Delta North",
  "Niger Delta West",
  "Okrika",
  "Ahoada",
  "Ogoni",
  "Etche",
  "Ikwerre",
  "Northern Izon",
  "Ogbia",
  "Evo",
  "Owerri",
  "Orlu",
  "Mbaise",
  "Isi Mbano",
  "Okigwe South",
  "Egbu",
  "Ideato",
  "Ohaji/Egbema",
  "On the Lake",
  "Oru",
  "Okigwe",
  "Ikeduru",
  "Aba",
  "Umuahia",
  "Ukwa",
  "Isuikwuato/Umunneochi",
  "Arochukwu/Ohafia",
  "Ikwuano",
  "Isiala Ngwa South",
  "Isiala Ngwa",
  "Aba Ngwa North",
  "Enugu",
  "Nsukka",
  "Abakiliki",
  "Oji River",
  "Awgu/Aninri",
  "Enugu North",
  "Ngbo",
  "Ikwo",
  "Afikpo",
  "Nike",
  "Udi",
  "Eha Amaufu",
];

export const parishes = [
  "Select Parish",
  "St. Paul’s Cathedral Parish",
  "St. John’s Anglican Parish",
  "All Saints Parish",
  "St. Mark’s Parish",
  "St. Andrew’s Parish",
  "St. Mary’s Parish",
  "Holy Trinity Parish",
  "St. Peter’s Parish",
  "Good Shepherd Parish",
  "Christ the King Parish",
];
